### ISSUE TITLE
.NET 8 raises `System.AccessViolationException` accessing fields

### ISSUE THREAD

**Issue by masesdevelopers** [masesgroup/JCOBridge#2]
Seems that the .NET Garbage Collector retires the `Org.Apache.Kafka.Streams.KeyValue<K, V>` object, releasing the underlying JVM object; this implies that the pointer stored is no more valid and the access to the data raises the exception. A possible workaround can be to instruct the .NET Garbage Collector to stop its execution around the critical region using [`GC.TryStartNoGCRegion`](https://learn.microsoft.com/en-us/dotnet/api/system.gc.trystartnogcregion?view=net-8.0#system-gc-trystartnogcregion(system-int64-system-boolean)) ending it with [`GC.EndNoGCRegion`](https://learn.microsoft.com/en-us/dotnet/api/system.gc.endnogcregion?view=net-8.0):

```C#
#if NET8_0
bool startedGCRegion = false;
startedGCRegion = GC.TryStartNoGCRegion(1024, false);
#endif

// critical region

#if NET8_0
if (startedGCRegion && GCSettings.LatencyMode == GCLatencyMode.NoGCRegion) GC.EndNoGCRegion();
#endif
```

The memory, in the previous example is 1024, can be changed based on the application using the `Org.Apache.Kafka.Streams.State.KeyValueIterator<K, V>`, the second parameter is set to `false` to avoid an usefulness full GC.

_Originally posted by @masesdevelopers in https://github.com/masesgroup/KNet/issues/345#issuecomment-1894574018_

**Comment by mariomastrodicasa** [comment]
Fixed in JCOBridge 2.5.10
